language: go
go:
  - "1.11"
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_1a8ba66f9725_key -iv $encrypted_1a8ba66f9725_iv -in .travis.key.enc -out .travis.key -d
install: go get github.com/gohugoio/hugo
script: bash ./.travis.sh
